### ISSUE TITLE
Config use_weighted_sum True or False?

### ISSUE THREAD

**Issue by RZ-Q** [catezi/MAPT#2]
Hi !
I have a question about the use_weighted_sum config used in your codes. As your default setting is False and it is not set in the bash file. But when use_weighted_sum is False, it seems to lose the attention across agent and time layer.

**Comment by catezi** [comment]
Hi,

The config of use_weighted_sum should be set to True. In practice, we find that learning preference model by using self-attention mechanism shows great advantages in longer sequence segments. It is suggested to choose whether to add self-attention mechanism according to the actual sequence length.

Thanks for your attention.
